setup:
  method: DataLens
  run_type: tfmp
  workdir: exp/datalens/mnist_eps1.0

public_data:
  name: null

sensitive_data:
  name: mnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_path: /p/fzv6enresearch/kecen/data
  test_path: /p/fzv6enresearch/kecen/data
  fid_stats: /p/fzv6enresearch/kecen/data/mnist_train.npz

model:
  sess: null
  image_size: 28
  dataset: mnist

  train: True
  load_d: True
  orders: 200
  z_dim: 50
  y_dim: 10
  tanh: False

  random_proj: False
  simple_gan: False
  pca: False
  wgan: False
  pca_dim: 10
  random_label: False
  save_vote: False
  batch_teachers: 50
  teachers_batch: 80

pretrain:
  log_dir: null

train:
  batch_size: 64
  epoch: 300
  non_private: False
  shuffle: True
  sigma: 5000
  sigma_thresh: 3000
  pretrain_teacher: 10
  topk: 200
  thresh: 0.7
  max_grad: 1e-5
  mean_kernel: False
  signsgd: True
  signsgd_nothresh: False
  klevelsgd: False
  sketchsgd: False
  signsgd_dept: False
  stochastic: True
  klevel: 4
  pca_sigma: 1.0
  step_size: 1e-4
  learning_rate: 1e-3
  proj_mat: 1
  g_step: 1
  d_step: 2
  beta1: 0.5
  save_vote: False
  increasing_dim: False
  save_epoch: False
  pretrain: False
  checkpoint_dir: checkpoint
  teacher_dir: teacher
  dp:
    delta: 1e-5
    epsilon: 1.

gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null

eval:
  batch_size: 1000