setup:
  method: dpsgd-gan
  run_type: torchmp
  n_gpus_per_node: 3
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dpgan/mnist_eps1.0

public_data:
  name: null

sensitive_data:
  name: mnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_path: /p/fzv6enresearch/kecen/data
  test_path: /p/fzv6enresearch/kecen/data
  fid_stats: /p/fzv6enresearch/kecen/data/mnist_train.npz

model:
  ckpt: null
  ema_rate: .999
  img_size: 28
  num_classes: 10
  Generator:
    z_dim: 60
    g_shared_dim: 128
    g_conv_dim: 96
    attn_g_loc: [2]
    apply_attn: True
  Discriminator:
    d_conv_dim: 80

pretrain:
  log_dir: null

train:
  log_dir: null
  seed: 0
  batch_size: 4096
  snapshot_batch_size: 80
  fid_batch_size: 256
  n_epochs: 150
  d_updates: 5
  log_freq: 10
  snapshot_freq: 10
  snapshot_threshold: 1
  save_freq: 100000
  save_threshold: 1
  fid_freq: 20
  fid_samples: 5000
  final_fid_samples: 60000
  fid_threshold: 1
  optim:
    optimizer: Adam
    params:
      d_lr: 5e-4
      g_lr: 2e-4
      beta1: 0.
  dp:
    sdq: null
    privacy_history: [[5, 0.1, 75]]
    alpha_num: 0
    max_grad_norm: 1.0
    delta: 1e-5
    epsilon: 1.
    max_physical_batch_size: 8192
    n_splits: 32

gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null

eval:
  batch_size: 1000