setup:
  method: GS-WGAN
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: 127.0.0.1
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dp-kernel/mnist_28_eps1.0
public_data:
  name: imagenet
  num_channels: 1
  resolution: 28
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
    ratio: 1.0
sensitive_data:
  name: fmnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_path: dataset/fmnist/train_28.zip
  test_path: dataset/fmnist/test_28.zip
  fid_stats: dataset/fmnist/fid_stats_28.npz
  train_num: all
model:
  ckpt: null
  num_discriminators: 1000
  gen_arch: ResNet
  c: 1
  img_size: 28
  z_dim: 10
  num_classes: 10
  model_dim: 64
  latent_type: bernoulli
pretrain:
  log_dir: null
  label_random: true
  seed: 0
  batch_size: 32
  iterations: 2000
  critic_iters: 5
  L_epsilon: 0.001
  L_gp: 10
  print_step: 100
  vis_step: 1000
  save_step: 5000
train:
  pretrain:
    log_dir: null
    label_random: false
    seed: 0
    batch_size: 32
    iterations: 2000
    critic_iters: 5
    L_epsilon: 0.001
    L_gp: 10
    print_step: 100
    vis_step: 1000
    save_step: 5000
  log_dir: null
  seed: 0
  batch_size: 32
  iterations: 20000
  critic_iters: 5
  L_epsilon: 0.001
  L_gp: 10
  print_step: 100
  vis_step: 1000
  save_step: 5000
  dp:
    epsilon: 10.0
    delta: 1e-5
gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
eval:
  mode: val
