setup:
  method: G-PATE
  run_type: tfmp
  workdir: exp/g_pate/mnist_28_eps1.0

public_data:
  name: imagenet
  num_channels: 1
  resolution: 28
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
    ratio: 1.0

sensitive_data:
  name: mnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_path: dataset/mnist/train_28.zip
  test_path: dataset/mnist/test_28.zip
  fid_stats: dataset/mnist/fid_stats_28.npz

model:
  sess: null
  image_size: 28
  dataset: mnist
  train: True
  load_d: True
  orders: 200
  z_dim: 100
  y_dim: 10
  tanh: False
  random_proj: True
  pca: False
  wgan: False
  pca_sigma: 1.0
  pca_dim: 10
  thresh: 0.5
  random_label: False
  # new flag
  batch_teachers: 50
  teachers_batch: 40

pretrain:
  log_dir: null
  batch_size: 64
  epoch: 1
  sigma: 100.
  sigma_thresh: 600.
  pca_sigma: 1.0
  step_size: 1e-4
  proj_mat: 1
  g_step: 1
  d_step: 1
  learning_rate: 1e-3
  beta1: 0.5
  shuffle: True
  increasing_dim: False
  save_epoch: False
  checkpoint_dir: checkpoint
  teacher_dir: teacher
  label_random: True

train:
  ckpt: null
  log_dir: null
  batch_size: 64
  epoch: 1000
  non_private: False
  sigma: 1000
  sigma_thresh: 3000
  pca_sigma: 1.0
  step_size: 1e-4
  proj_mat: 1
  g_step: 1
  d_step: 1
  learning_rate: 1e-3
  beta1: 0.5
  shuffle: True
  increasing_dim: False
  save_epoch: False
  pretrain: False
  checkpoint_dir: checkpoint
  teacher_dir: teacher
  dp:
    delta: 1e-5
    epsilon: 10.

gen:
  data_num: 60000
  batch_size: 1000
  num_channels: 1
  resolution: 28
  log_dir: null

eval:
  batch_size: 1000