setup:
  method: G-PATE
  run_type: tfmp
  workdir: exp/g_pate/mnist_eps1.0

public_data:
  name: null

sensitive_data:
  name: mnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_path: /p/fzv6enresearch/kecen/data
  test_path: /p/fzv6enresearch/kecen/data
  fid_stats: /p/fzv6enresearch/kecen/data/mnist_train.npz

model:
  sess: null
  image_size: 28
  dataset: mnist
  train: True
  load_d: True
  orders: 200
  z_dim: 50
  y_dim: 10
  tanh: False
  random_proj: True
  pca: False
  wgan: False
  pca_sigma: 1.0
  pca_dim: 10
  thresh: 0.5
  random_label: False
  shuffle: False
  # new flag
  batch_teachers: 100
  teachers_batch: 40
  sample_step: 10

pretrain:
  log_dir: null

train:
  batch_size: 64
  epoch: 1000
  non_private: False
  sigma: 1000
  sigma_thresh: 3000
  pca_sigma: 1.0
  step_size: 1e-4
  proj_mat: 1
  g_step: 1
  d_step: 1
  learning_rate: 1e-3
  beta1: 0.5
  increasing_dim: False
  save_epoch: True
  pretrain: False
  checkpoint_dir: checkpoint
  teacher_dir: teacher
  dp:
    delta: 1e-5
    epsilon: 1.

gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null

eval:
  batch_size: 1000