setup:
  method: DPSDA
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dpsda/placeholder

public_data:
  name: null

sensitive_data:
  name: camelyon_32
  num_channels: 3
  resolution: 32
  n_classes: 2
  train_path: /tmp/zinanlin/tmp/DPImageBench/dataset/camelyon/train_32.zip
  test_path: /tmp/zinanlin/tmp/DPImageBench/dataset/camelyon/test_32.zip
  fid_stats: /tmp/zinanlin/tmp/DPImageBench/dataset/camelyon/fid_stats_32.npz
  train_num: all

model:
  api: improved_diffusion
  feature_extractor: inception_v3
  api_params:
    model_image_size: 64
    num_channels: 192
    num_res_blocks: 3
    learn_sigma: True
    class_cond: True
    diffusion_steps: 4000
    noise_schedule: cosine
    rescale_learned_sigmas: False
    rescale_timesteps: False
    use_ddim: True
    timestep_respacing: ddim10
    batch_size: 2000
    model_path: /tmp/zinanlin/tmp/DPImageBench/pretrained_models/imagenet64_cond_270M_250K.pt

pretrain:
  log_dir: null

train:
  batch_size: 2000
  feature_extractor_batch_size: 500
  private_image_size: 32
  private_num_classes: 2
  num_samples_schedule: [60000,60000,60000,60000,60000,60000,60000,60000]
  variation_degree_schedule: [0,0,0,0,0,1,1,1]
  initial_prompt: null
  image_size: 64x64
  lookahead_degree: 8
  num_nearest_neighbor: 1
  nn_mode: L2
  count_threshold: 4.0
  log_dir: null
  tmp_folder: /tmp/zinanlin/tmp/DPImageBench/dataset/camelyon/dpsda_tmp
  dp:
    epsilon: 10.0
    delta: 1e-5

gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
  num_channels: 3
  resolution: 32


eval:
  batch_size: 1000