setup:
  method: DPSDA
  torchmp: False
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dp-merf/cifar10_eps1.0

public_data:
  name: null

sensitive_data:
  name: cifar10
  num_channels: 3
  resolution: 32
  n_classes: 10
  train_path: /p/fzv6enresearch/kecen/data
  test_path: /p/fzv6enresearch/kecen/data
  fid_stats: /p/fzv6enresearch/kecen/data/cifar10_train.zip

model:
  api: improved_diffusion
  feature_extractor: inception_v3
  api_params:
    model_image_size: 64
    num_channels: 192
    num_res_blocks: 3
    learn_sigma: True
    class_cond: True
    diffusion_steps: 4000
    noise_schedule: cosine
    rescale_learned_sigmas: False
    rescale_timesteps: False
    use_ddim: True
    timestep_respacing: 50
    batch_size: 1000
    model_path: models/pretrained_models/imagenet64_cond_270M_250K.pt

pretrain:
  null

train:
  feature_extractor_batch_size: 500
  private_image_size: 32
  private_num_classes: 10
  num_samples_schedule: [50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000,50000]
  variation_degree_schedule: [0,2,4,6,8,10,12,14,16,18]
  initial_prompt: null
  image_size: 64x64
  lookahead_degree: 8
  num_nearest_neighbor: 1
  nn_mode: L2
  count_threshold: 10.0
  log_dir: null
  dp:
    epsilon: 1.0
    delta: 1e-5

gen:
  data_num: 50000
  batch_size: 1000
  log_dir: null
  num_channels: 3
  resolution: 32