setup:
  method: DPSDA
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dpsda/mnist_28_eps10.0_th2.5_tr10_vds000111222333

public_data:
  name: null

sensitive_data:
  name: mnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_path: /tmp/zinanlin/tmp/DPImageBench/dataset/mnist/train_28.zip
  test_path: /tmp/zinanlin/tmp/DPImageBench/dataset/mnist/test_28.zip
  fid_stats: /tmp/zinanlin/tmp/DPImageBench/dataset/mnist/fid_stats_28.npz

model:
  api: improved_diffusion
  feature_extractor: inception_v3
  api_params:
    model_image_size: 64
    num_channels: 192
    num_res_blocks: 3
    learn_sigma: True
    class_cond: True
    diffusion_steps: 4000
    noise_schedule: cosine
    rescale_learned_sigmas: False
    rescale_timesteps: False
    use_ddim: True
    timestep_respacing: 10
    batch_size: 2000
    model_path: /tmp/zinanlin/tmp/DPImageBench/pretrained_models/imagenet64_cond_270M_250K.pt

pretrain:
  log_dir: null

train:
  batch_size: 2000
  feature_extractor_batch_size: 500
  private_image_size: 28
  private_num_classes: 10
  num_samples_schedule: [60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000,60000]
  variation_degree_schedule: [0,0,0,1,1,1,2,2,2,3,3,3]
  initial_prompt: null
  image_size: 64x64
  lookahead_degree: 8
  num_nearest_neighbor: 1
  nn_mode: L2
  count_threshold: 2.5
  log_dir: null
  tmp_folder: /tmp/zinanlin/tmp/DPImageBench/dataset/mnist/dpsda_tmp
  dp:
    epsilon: 10.0
    delta: 1e-5

gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
  num_channels: 1
  resolution: 28


eval:
  batch_size: 1000