setup:
  method: DP-MERF
  torchmp: False
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dp-merf/cifar10_eps1.0

public_data:
  name: null

sensitive_data:
  name: cifar10
  num_channels: 3
  resolution: 32
  n_classes: 10
  train_path: /p/fzv6enresearch/kecen/data
  test_path: /p/fzv6enresearch/kecen/data
  fid_stats: /p/fzv6enresearch/kecen/data/cifar10_train.zip

model:
  z_dim: 5
  h_dim: '200'
  num_class: 10
  n_channels: '16,8,3'
  kernel_sizes: '5,5'
  n_feat: 3072
  d_rff: 10000
  rff_sigma: '105'
  mmd_type: sphere

pretrain:
  null

train:
  epochs: 5
  batch_size: 100
  lr: 0.01
  lr_decay: 0.9
  log_interval: 10000
  n_data: 60000
  log_dir: exp/dp-merf/mnist_eps1.0/train/
  num_channels: 3
  resolution: 32
  dp:
    epsilon: 1.0
    delta: 1e-5

gen:
  data_num: 60000
  batch_size: 1000
  log_dir: exp/dp-merf/mnist_eps1.0/gen/
  num_channels: 3
  resolution: 32

eval:
  batch_size: 1000