setup:
  method: DP-MERF
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: 127.0.0.1
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dp-merf/mnist_28_eps1.0
public_data:
  name: imagenet
  num_channels: 1
  resolution: 28
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
    ratio: 1.0
sensitive_data:
  name: fmnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_num: all
  train_path: dataset/fmnist/train_28.zip
  test_path: dataset/fmnist/test_28.zip
  fid_stats: dataset/fmnist/fid_stats_28.npz
model:
  num_class: 10
  img_size: 28
  Generator:
    z_dim: 60
    g_shared_dim: 128
    g_conv_dim: 41
    attn_g_loc:
    - 2
    apply_attn: true
  n_feat: 784
  d_rff: 10000
  rff_sigma: '105'
  mmd_type: sphere
pretrain:
  log_dir: null
  epochs: 1
  batch_size: 100
  lr: 0.01
  lr_decay: 0.9
  log_interval: 10000
  label_random: true
train:
  ckpt: null
  epochs: 5
  batch_size: 100
  lr: 0.01
  lr_decay: 0.9
  log_interval: 10000
  log_dir: null
  num_channels: 1
  resolution: 28
  dp:
    epsilon: 10.0
    delta: 1e-5
gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
  num_channels: 1
  resolution: 28
eval:
  batch_size: 1000
