setup:
  method: DP-MERF
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dp-merf/mnist_28_eps1.0

public_data:
  name: imagenet
  num_channels: 1
  resolution: 28
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
    ratio: 1.0

sensitive_data:
  name: mnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_path: dataset/mnist/train_28.zip
  test_path: dataset/mnist/test_28.zip
  fid_stats: dataset/mnist/fid_stats_28.npz

model:
  z_dim: 5
  h_dim: '200'
  num_class: 10
  n_channels: '16,8,1'
  kernel_sizes: '5,5'
  n_feat: 784
  d_rff: 10000
  rff_sigma: '105'
  mmd_type: sphere

pretrain:
  log_dir: null
  epochs: 5
  batch_size: 100
  lr: 0.01
  lr_decay: 0.9
  log_interval: 10000
  label_random: True

train:
  ckpt: null
  epochs: 5
  batch_size: 100
  lr: 0.01
  lr_decay: 0.9
  log_interval: 10000
  log_dir: null
  num_channels: 1
  resolution: 28
  dp:
    epsilon: 1.0
    delta: 1e-5

gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
  num_channels: 1
  resolution: 28

eval:
  batch_size: 1000