setup:
  method: DP-NTK
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: 127.0.0.1
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dp-ntk/mnist_28_eps1.0
public_data:
  name: imagenet
  num_channels: 3
  resolution: 32
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
    ratio: 1.0
sensitive_data:
  name: celeba_male_32
  num_channels: 3
  resolution: 32
  n_classes: 2
  train_path: dataset/celeba/train_32_Male.zip
  test_path: dataset/celeba/test_32_Male.zip
  fid_stats: dataset/celeba/fid_stats_32.npz
model:
  model_ntk: fc_2l
  ntk_width: 32
  ntk_width2: 256
  img_size: 32
  c: 3
  n_classes: 2
  z_dim: 201
  h_dim: '200'
  n_channels: 16,8
  kernel_sizes: 5,5
pretrain:
  log_dir: null
  n_iter: 4000
  batch_size: 5000
  lr: 1e-2
  lr_decay: 0.9
  scheduler_interval: 2001
  log_interval: 100
  cond: true
train:
  ckpt: null
  n_iter: 2000
  batch_size: 5000
  lr: 1e-2
  lr_decay: 0.9
  scheduler_interval: 2001
  log_interval: 100
  log_dir: null
  dp:
    epsilon: 1.0
    delta: 1e-6
gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
eval:
  batch_size: 1000
  mode: val
