setup:
  method: DP-NTK
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: 127.0.0.1
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dp-ntk/mnist_28_eps10.0
public_data:
  name: imagenet
  num_channels: 1
  resolution: 28
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
    ratio: 1.0
sensitive_data:
  name: fmnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_path: dataset/fmnist/train_28.zip
  test_path: dataset/fmnist/test_28.zip
  fid_stats: dataset/fmnist/fid_stats_28.npz
  train_num: all
model:
  model_ntk: fc_2l
  ntk_width: 32
  ntk_width2: 256
  img_size: 28
  c: 1
  Generator:
    z_dim: 60
    g_shared_dim: 128
    g_conv_dim: 41
    attn_g_loc:
    - 2
    apply_attn: true
  n_classes: 10
pretrain:
  log_dir: null
  n_iter: 2000
  batch_size: 2500
  lr: 1e-2
  lr_decay: 0.9
  scheduler_interval: 2001
  log_interval: 100
  label_random: true
train:
  ckpt: null
  n_iter: 2000
  batch_size: 5000
  lr: 1e-2
  lr_decay: 0.9
  scheduler_interval: 2001
  log_interval: 100
  log_dir: null
  dp:
    epsilon: 10.0
    delta: 1e-5
gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
eval:
  batch_size: 1000
