setup:
  method: DP-Kernel
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dp-kernel/mnist_eps1.0

public_data:
  name: null

sensitive_data:
  name: mnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_path: /p/fzv6enresearch/kecen/data
  test_path: /p/fzv6enresearch/kecen/data
  fid_stats: /p/fzv6enresearch/kecen/data/mnist_train.npz

model:
  image_size: 32
  nc: 1
  nz: 10
  ngf: 64
  n_class: 10
  sigma_list: [1, 2, 4, 8, 16]

pretrain:
  log_dir: null

train:
  max_iter: 200002
  batch_size: 60
  lr: 5e-5
  vis_step: 10000
  log_dir: null
  dp:
    epsilon: 1.0
    delta: 1e-5

gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null

eval:
  batch_size: 1000