setup:
  method: DP-Kernel
  torchmp: False
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dp-kernel/cifar10_eps1.0

public_data:
  name: null

sensitive_data:
  name: cifar10
  num_channels: 3
  resolution: 32
  n_classes: 10
  train_path: /p/fzv6enresearch/kecen/data
  test_path: /p/fzv6enresearch/kecen/data
  fid_stats: /p/fzv6enresearch/kecen/data/cifar10_train.zip

model:
  image_size: 32
  nc: 3
  nz: 10
  ngf: 64
  n_class: 10
  sigma_list: [1, 2, 4, 8, 16]

pretrain:
  null

train:
  max_iter: 200002
  batch_size: 60
  lr: 5e-5
  vis_step: 10000
  log_dir: exp/dp-merf/mnist_eps1.0/train/
  dp:
    epsilon: 1.0
    delta: 1e-5

gen:
  data_num: 60000
  batch_size: 1000
  log_dir: exp/dp-merf/mnist_eps1.0/gen/
  num_channels: 3
  resolution: 32

eval:
  batch_size: 1000