setup:
  method: DP-Kernel
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dp-kernel/mnist_28_eps1.0

public_data:
  name: imagenet
  num_channels: 1
  resolution: 28
  n_classes: 1000
  train_path: dataset/imagenet/imagenet_32
  selective:
  ratio: 1.0

sensitive_data:
  name: fmnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_path: dataset/fmnist/train_28.zip
  test_path: dataset/fmnist/test_28.zip
  fid_stats: dataset/fmnist/fid_stats_28.npz

model:
  image_size: 32
  nc: 1
  nz: 10
  ngf: 64
  n_class: 10
  sigma_list: [1, 2, 4, 8, 16]

pretrain:
  log_dir: null
  n_epochs: 1
  lr: 5e-5
  batch_size: 60
  label_random: True

train:
  ckpt: null
  max_iter: 200002
  batch_size: 60
  lr: 5e-5
  vis_step: 10000
  log_dir: null
  dp:
    epsilon: 1.0
    delta: 1e-5

gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null

eval:
  batch_size: 1000