setup:
  method: DP-NTK
  run_type: normal
  n_gpus_per_node: 1
  n_nodes: 1
  node_rank: 0
  master_address: '127.0.0.1'
  master_port: 6025
  omp_n_threads: 8
  workdir: exp/dp-ntk/mnist_eps1.0

public_data:
  name: null

sensitive_data:
  name: mnist
  num_channels: 1
  resolution: 28
  n_classes: 10
  train_path: /u/fzv6en/kecen/data
  test_path: /u/fzv6en/kecen/data
  fid_stats: /u/fzv6en/kecen/data/mnist_train.npz

model:
  model_ntk: fc_1l
  ntk_width: 800
  input_dim: 784
  n_classes: 10

  z_dim: 5
  h_dim: '200'
  n_channels: '16,8,1'
  kernel_sizes: '5,5'

pretrain:
  log_dir: null

train:
  n_iter: 2000
  batch_size: 5000
  lr: 1e-2
  lr_decay: 0.9
  scheduler_interval: 2001
  log_interval: 100
  log_dir: null
  dp:
    epsilon: 1.0
    delta: 1e-5

gen:
  data_num: 60000
  batch_size: 1000
  log_dir: null
  num_channels: 1
  resolution: 28

eval:
  batch_size: 1000